// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SsoBackend.Data;

#nullable disable

namespace SsoBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConsentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JsonWebKeySet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Permissions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostLogoutRedirectUris")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RedirectUris")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Settings")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasFilter("[ClientId] IS NOT NULL");

                    b.ToTable("OpenIddictApplications", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Scopes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictAuthorizations", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreScope", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descriptions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resources")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("OpenIddictScopes", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AuthorizationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId");

                    b.HasIndex("ReferenceId")
                        .IsUnique()
                        .HasFilter("[ReferenceId] IS NOT NULL");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictTokens", (string)null);
                });

            modelBuilder.Entity("SsoBackend.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("GcsUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SsoBackend.Models.Approval.ApprovalPengajuan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("IdAtasan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("id_atasan");

                    b.Property<string>("IdKaryawan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("id_karyawan");

                    b.Property<string>("IdManager")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("id_manager");

                    b.Property<string>("Jenis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("jenis");

                    b.Property<string>("Komentar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("komentar");

                    b.Property<string>("Nama")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama");

                    b.Property<string>("RefId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ref_id");

                    b.Property<string>("Ringkasan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ringkasan");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("TglKeputusan")
                        .HasColumnType("datetime2")
                        .HasColumnName("tgl_keputusan");

                    b.Property<DateTime>("TglPengajuan")
                        .HasColumnType("datetime2")
                        .HasColumnName("tgl_pengajuan");

                    b.HasKey("Id");

                    b.ToTable("pengajuan", "approval", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SsoBackend.Models.Aset.Aset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Catatan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("catatan");

                    b.Property<string>("IdPembuat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("id_pembuat");

                    b.Property<string>("IdPic")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("id_pic");

                    b.Property<string>("Kategori")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kategori");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kode");

                    b.Property<string>("Kondisi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kondisi");

                    b.Property<string>("Lokasi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lokasi");

                    b.Property<string>("Merk")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("merk");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama");

                    b.Property<string>("NamaPic")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama_pic");

                    b.Property<decimal?>("Nilai")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("nilai");

                    b.Property<string>("NomorSeri")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nomor_seri");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<DateTime>("TglDibuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("tgl_dibuat");

                    b.Property<DateTime?>("TglDiubah")
                        .HasColumnType("datetime2")
                        .HasColumnName("tgl_diubah");

                    b.Property<DateOnly?>("TglPerolehan")
                        .HasColumnType("date")
                        .HasColumnName("tgl_perolehan");

                    b.HasKey("Id");

                    b.ToTable("aset", "aset", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SsoBackend.Models.Aset.AsetMaintenance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Biaya")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("biaya");

                    b.Property<string>("Catatan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("catatan");

                    b.Property<long>("IdAset")
                        .HasColumnType("bigint")
                        .HasColumnName("id_aset");

                    b.Property<string>("IdPembuat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("id_pembuat");

                    b.Property<string>("Jenis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("jenis");

                    b.Property<string>("Pelaksana")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pelaksana");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<DateTime>("TglDibuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("tgl_dibuat");

                    b.Property<DateOnly>("TglJadwal")
                        .HasColumnType("date")
                        .HasColumnName("tgl_jadwal");

                    b.Property<DateOnly?>("TglSelesai")
                        .HasColumnType("date")
                        .HasColumnName("tgl_selesai");

                    b.HasKey("Id");

                    b.ToTable("maintenance", "aset", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SsoBackend.Models.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Accuracy")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("CatatanMangkir")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CheckIn")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CheckOut")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodePegawai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Lat")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("Lng")
                        .HasPrecision(11, 7)
                        .HasColumnType("decimal(11,7)");

                    b.Property<string>("NamaHari")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NamaPegawai")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("Tanggal")
                        .HasColumnType("date");

                    b.Property<string>("Tempat")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KodePegawai", "Tanggal");

                    b.ToTable("attendances", (string)null);
                });

            modelBuilder.Entity("SsoBackend.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("EventType");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("SsoBackend.Models.Coaching.CoachingBaca", b =>
                {
                    b.Property<string>("Nik")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("nik");

                    b.Property<string>("Kanal")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("kanal");

                    b.Property<DateTime>("TglBaca")
                        .HasColumnType("datetime2")
                        .HasColumnName("tgl_baca");

                    b.HasKey("Nik", "Kanal");

                    b.ToTable("baca", "coaching", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SsoBackend.Models.Coaching.CoachingPesan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("IdPengirim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("id_pengirim");

                    b.Property<long?>("IdSesi")
                        .HasColumnType("bigint")
                        .HasColumnName("id_sesi");

                    b.Property<string>("Isi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("isi");

                    b.Property<string>("NamaPengirim")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama_pengirim");

                    b.Property<string>("RuangNik")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ruang_nik");

                    b.Property<DateTime>("TglKirim")
                        .HasColumnType("datetime2")
                        .HasColumnName("tgl_kirim");

                    b.HasKey("Id");

                    b.ToTable("pesan", "coaching", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SsoBackend.Models.Coaching.CoachingSesi", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("IdAtasan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("id_atasan");

                    b.Property<string>("IdBawahan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("id_bawahan");

                    b.Property<string>("IdPembuat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("id_pembuat");

                    b.Property<string>("NamaAtasan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama_atasan");

                    b.Property<string>("NamaBawahan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama_bawahan");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<DateTime>("TglDibuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("tgl_dibuat");

                    b.Property<DateTime?>("TglTerakhir")
                        .HasColumnType("datetime2")
                        .HasColumnName("tgl_terakhir");

                    b.Property<string>("Topik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("topik");

                    b.HasKey("Id");

                    b.ToTable("sesi", "coaching", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SsoBackend.Models.Coaching.CoachingTindakLanjut", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("IdPembuat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("id_pembuat");

                    b.Property<long>("IdSesi")
                        .HasColumnType("bigint")
                        .HasColumnName("id_sesi");

                    b.Property<string>("Isi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("isi");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<DateTime>("TglDibuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("tgl_dibuat");

                    b.Property<DateTime?>("TglSelesai")
                        .HasColumnType("datetime2")
                        .HasColumnName("tgl_selesai");

                    b.HasKey("Id");

                    b.ToTable("tindak_lanjut", "coaching", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SsoBackend.Models.Cuti.CutiPengajuan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("IdAtasan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("id_atasan");

                    b.Property<string>("IdKaryawan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("id_karyawan");

                    b.Property<int>("JumlahHari")
                        .HasColumnType("int")
                        .HasColumnName("jumlah_hari");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("keterangan");

                    b.Property<string>("Komentar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("komentar");

                    b.Property<string>("Nama")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("TglKeputusan")
                        .HasColumnType("datetime2")
                        .HasColumnName("tgl_keputusan");

                    b.Property<DateOnly>("TglMulai")
                        .HasColumnType("date")
                        .HasColumnName("tgl_mulai");

                    b.Property<DateTime>("TglPengajuan")
                        .HasColumnType("datetime2")
                        .HasColumnName("tgl_pengajuan");

                    b.Property<DateOnly>("TglSelesai")
                        .HasColumnType("date")
                        .HasColumnName("tgl_selesai");

                    b.HasKey("Id");

                    b.ToTable("pengajuan", "cuti", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SsoBackend.Models.Cuti.CutiSaldo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CutiBersama")
                        .HasColumnType("int")
                        .HasColumnName("cuti_bersama");

                    b.Property<int>("Diambil")
                        .HasColumnType("int")
                        .HasColumnName("diambil");

                    b.Property<DateTime>("DibuatPada")
                        .HasColumnType("datetime2")
                        .HasColumnName("dibuat_pada");

                    b.Property<DateTime>("DiperbaruiPada")
                        .HasColumnType("datetime2")
                        .HasColumnName("diperbarui_pada");

                    b.Property<int>("Hak")
                        .HasColumnType("int")
                        .HasColumnName("hak");

                    b.Property<string>("IdKaryawan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("id_karyawan");

                    b.Property<string>("Nama")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama");

                    b.Property<string>("Periode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("periode");

                    b.Property<int>("Saldo")
                        .HasColumnType("int")
                        .HasColumnName("saldo");

                    b.Property<DateOnly?>("TglCutoff")
                        .HasColumnType("date")
                        .HasColumnName("tgl_cutoff");

                    b.Property<DateOnly?>("Tmt")
                        .HasColumnType("date")
                        .HasColumnName("tmt");

                    b.HasKey("Id");

                    b.ToTable("saldo", "cuti", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SsoBackend.Models.Cuti.CutiSetelan", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("id");

                    b.Property<int>("CutiBersama")
                        .HasColumnType("int")
                        .HasColumnName("cuti_bersama");

                    b.Property<string>("DiperbaruiOleh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("diperbarui_oleh");

                    b.Property<DateTime?>("DiperbaruiPada")
                        .HasColumnType("datetime2")
                        .HasColumnName("diperbarui_pada");

                    b.Property<int>("HakDasar")
                        .HasColumnType("int")
                        .HasColumnName("hak_dasar");

                    b.HasKey("Id");

                    b.ToTable("setelan", "cuti", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SsoBackend.Models.Gaji.GajiKomponen", b =>
                {
                    b.Property<int>("IdKomponen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_komponen");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKomponen"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit")
                        .HasColumnName("aktif");

                    b.Property<string>("Basis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("basis");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kategori");

                    b.Property<bool>("KenaPotonganTerlambat")
                        .HasColumnType("bit")
                        .HasColumnName("kena_potongan_terlambat");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("keterangan");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kode");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama");

                    b.Property<bool>("Opsional")
                        .HasColumnType("bit")
                        .HasColumnName("opsional");

                    b.Property<string>("Tipe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipe");

                    b.Property<int>("Urutan")
                        .HasColumnType("int")
                        .HasColumnName("urutan");

                    b.HasKey("IdKomponen");

                    b.ToTable("komponen", "gaji", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SsoBackend.Models.Gaji.GajiPeriode", b =>
                {
                    b.Property<int>("IdPeriode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_periode");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPeriode"));

                    b.Property<byte>("Bulan")
                        .HasColumnType("tinyint")
                        .HasColumnName("bulan");

                    b.Property<DateTime>("DibuatPada")
                        .HasColumnType("datetime2")
                        .HasColumnName("dibuat_pada");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<short>("Tahun")
                        .HasColumnType("smallint")
                        .HasColumnName("tahun");

                    b.HasKey("IdPeriode");

                    b.ToTable("periode", "gaji", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SsoBackend.Models.Gaji.GajiSlip", b =>
                {
                    b.Property<long>("IdSlip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_slip");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdSlip"));

                    b.Property<DateTime>("DibuatPada")
                        .HasColumnType("datetime2")
                        .HasColumnName("dibuat_pada");

                    b.Property<byte?>("IdBand")
                        .HasColumnType("tinyint")
                        .HasColumnName("id_band");

                    b.Property<string>("IdKaryawan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("id_karyawan");

                    b.Property<int>("IdPeriode")
                        .HasColumnType("int")
                        .HasColumnName("id_periode");

                    b.Property<string>("Jabatan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("jabatan");

                    b.Property<byte?>("Jg")
                        .HasColumnType("tinyint")
                        .HasColumnName("jg");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama");

                    b.Property<byte?>("Pg")
                        .HasColumnType("tinyint")
                        .HasColumnName("pg");

                    b.Property<decimal>("PotonganTerlambat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("potongan_terlambat");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("Tingkatan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tingkatan");

                    b.HasKey("IdSlip");

                    b.ToTable("slip", "gaji", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SsoBackend.Models.Gaji.GajiSlipDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("IdKomponen")
                        .HasColumnType("int")
                        .HasColumnName("id_komponen");

                    b.Property<long>("IdSlip")
                        .HasColumnType("bigint")
                        .HasColumnName("id_slip");

                    b.Property<decimal>("Nominal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("nominal");

                    b.HasKey("Id");

                    b.ToTable("slip_detail", "gaji", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SsoBackend.Models.Gaji.GajiTarif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdKomponen")
                        .HasColumnType("int")
                        .HasColumnName("id_komponen");

                    b.Property<byte>("Jg")
                        .HasColumnType("tinyint")
                        .HasColumnName("jg");

                    b.Property<decimal>("Nominal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("nominal");

                    b.Property<byte>("Pg")
                        .HasColumnType("tinyint")
                        .HasColumnName("pg");

                    b.Property<short>("TahunBerlaku")
                        .HasColumnType("smallint")
                        .HasColumnName("tahun_berlaku");

                    b.HasKey("Id");

                    b.ToTable("tarif", "gaji", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SsoBackend.Models.Health.HealthHasil", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Berat")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("berat");

                    b.Property<string>("IdPencatat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("id_pencatat");

                    b.Property<long>("IdPeriode")
                        .HasColumnType("bigint")
                        .HasColumnName("id_periode");

                    b.Property<byte[]>("Konten")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("konten");

                    b.Property<string>("Nama")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama");

                    b.Property<string>("NamaFile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama_file");

                    b.Property<string>("NamaPencatat")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama_pencatat");

                    b.Property<string>("Nik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nik");

                    b.Property<string>("Rekomendasi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rekomendasi");

                    b.Property<string>("Ringkasan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ringkasan");

                    b.Property<string>("StatusTindakLanjut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status_tindak_lanjut");

                    b.Property<string>("StatusUmum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status_umum");

                    b.Property<string>("TekananDarah")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tekanan_darah");

                    b.Property<DateTime>("TglDicatat")
                        .HasColumnType("datetime2")
                        .HasColumnName("tgl_dicatat");

                    b.Property<DateTime?>("TglDiubah")
                        .HasColumnType("datetime2")
                        .HasColumnName("tgl_diubah");

                    b.Property<DateOnly?>("TglPemeriksaan")
                        .HasColumnType("date")
                        .HasColumnName("tgl_pemeriksaan");

                    b.Property<decimal?>("Tinggi")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tinggi");

                    b.Property<string>("TipeFile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipe_file");

                    b.HasKey("Id");

                    b.ToTable("hasil", "health", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SsoBackend.Models.Health.HealthPeriode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Catatan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("catatan");

                    b.Property<string>("IdPembuat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("id_pembuat");

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("judul");

                    b.Property<string>("Lokasi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lokasi");

                    b.Property<string>("Penyelenggara")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("penyelenggara");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<int>("Tahun")
                        .HasColumnType("int")
                        .HasColumnName("tahun");

                    b.Property<DateTime>("TglDibuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("tgl_dibuat");

                    b.Property<DateTime?>("TglDiubah")
                        .HasColumnType("datetime2")
                        .HasColumnName("tgl_diubah");

                    b.Property<DateOnly?>("TglMulai")
                        .HasColumnType("date")
                        .HasColumnName("tgl_mulai");

                    b.Property<DateOnly?>("TglSelesai")
                        .HasColumnType("date")
                        .HasColumnName("tgl_selesai");

                    b.HasKey("Id");

                    b.ToTable("periode", "health", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SsoBackend.Models.Kpi.Kpi", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Bobot")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("bobot");

                    b.Property<string>("Catatan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("catatan");

                    b.Property<string>("Deskripsi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("deskripsi");

                    b.Property<long?>("IdParent")
                        .HasColumnType("bigint")
                        .HasColumnName("id_parent");

                    b.Property<string>("IdPembuat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("id_pembuat");

                    b.Property<string>("IdPemilik")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("id_pemilik");

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("judul");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("level");

                    b.Property<string>("NamaPembuat")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama_pembuat");

                    b.Property<string>("NamaPemilik")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama_pemilik");

                    b.Property<string>("Periode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("periode");

                    b.Property<decimal>("Realisasi")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("realisasi");

                    b.Property<string>("Satuan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("satuan");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<decimal>("Target")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("target");

                    b.Property<DateTime>("TglDibuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("tgl_dibuat");

                    b.Property<DateTime?>("TglDiubah")
                        .HasColumnType("datetime2")
                        .HasColumnName("tgl_diubah");

                    b.HasKey("Id");

                    b.ToTable("kpi", "kpi", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SsoBackend.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Lat")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("Lng")
                        .HasPrecision(11, 7)
                        .HasColumnType("decimal(11,7)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("RadiusMeters")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Aktif");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("SsoBackend.Models.ModuleAccess", b =>
                {
                    b.Property<string>("ModuleKey")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Access")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("ModuleKey");

                    b.ToTable("module_access", (string)null);
                });

            modelBuilder.Entity("SsoBackend.Models.Office.Notifikasi", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DibacaPada")
                        .HasColumnType("datetime2")
                        .HasColumnName("dibaca_pada");

                    b.Property<DateTime>("DibuatPada")
                        .HasColumnType("datetime2")
                        .HasColumnName("dibuat_pada");

                    b.Property<long?>("IdSurat")
                        .HasColumnType("bigint")
                        .HasColumnName("id_surat");

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("judul");

                    b.Property<string>("Nik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nik");

                    b.Property<string>("OlehJabatan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("oleh_jabatan");

                    b.Property<string>("OlehNama")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("oleh_nama");

                    b.Property<string>("OlehNik")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("oleh_nik");

                    b.HasKey("Id");

                    b.ToTable("notifikasi", "office", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SsoBackend.Models.Office.RefBagian", b =>
                {
                    b.Property<string>("Kode")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("kode");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit")
                        .HasColumnName("aktif");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama");

                    b.Property<int>("Urutan")
                        .HasColumnType("int")
                        .HasColumnName("urutan");

                    b.HasKey("Kode");

                    b.ToTable("ref_bagian", "office", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SsoBackend.Models.Office.RefBagianUnit", b =>
                {
                    b.Property<string>("NamaUnit")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("nama_unit");

                    b.Property<string>("KodeBagian")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kode_bagian");

                    b.Property<string>("Tingkat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tingkat");

                    b.HasKey("NamaUnit");

                    b.ToTable("ref_bagian_unit", "office", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SsoBackend.Models.Office.RefJenisSurat", b =>
                {
                    b.Property<string>("Kode")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("kode");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit")
                        .HasColumnName("aktif");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama");

                    b.Property<int>("Urutan")
                        .HasColumnType("int")
                        .HasColumnName("urutan");

                    b.HasKey("Kode");

                    b.ToTable("ref_jenis_surat", "office", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SsoBackend.Models.Office.RefKlasifikasi", b =>
                {
                    b.Property<string>("Kode")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("kode");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit")
                        .HasColumnName("aktif");

                    b.Property<string>("Kelompok")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kelompok");

                    b.Property<string>("Masalah")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("masalah");

                    b.HasKey("Kode");

                    b.ToTable("ref_klasifikasi", "office", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SsoBackend.Models.Office.Surat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("BerlakuMulai")
                        .HasColumnType("date")
                        .HasColumnName("berlaku_mulai");

                    b.Property<DateOnly?>("BerlakuSampai")
                        .HasColumnType("date")
                        .HasColumnName("berlaku_sampai");

                    b.Property<DateTime>("DibuatPada")
                        .HasColumnType("datetime2")
                        .HasColumnName("dibuat_pada");

                    b.Property<DateTime>("DiperbaruiPada")
                        .HasColumnType("datetime2")
                        .HasColumnName("diperbarui_pada");

                    b.Property<string>("Isi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("isi");

                    b.Property<string>("Jenis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("jenis");

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("judul");

                    b.Property<string>("Kecepatan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kecepatan");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("keterangan");

                    b.Property<string>("Klasifikasi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("klasifikasi");

                    b.Property<string>("KodeBagian")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kode_bagian");

                    b.Property<string>("KodeKlasifikasi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kode_klasifikasi");

                    b.Property<string>("Nomor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nomor");

                    b.Property<string>("PembuatNama")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pembuat_nama");

                    b.Property<string>("PembuatNik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pembuat_nik");

                    b.Property<string>("Sifat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sifat");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<DateOnly?>("TanggalSurat")
                        .HasColumnType("date")
                        .HasColumnName("tanggal_surat");

                    b.HasKey("Id");

                    b.ToTable("surat", "office", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SsoBackend.Models.Office.SuratDibaca", b =>
                {
                    b.Property<long>("IdSurat")
                        .HasColumnType("bigint")
                        .HasColumnName("id_surat");

                    b.Property<string>("Nik")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("nik");

                    b.Property<DateTime>("DibacaPada")
                        .HasColumnType("datetime2")
                        .HasColumnName("dibaca_pada");

                    b.HasKey("IdSurat", "Nik");

                    b.ToTable("surat_dibaca", "office", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SsoBackend.Models.Office.SuratDistribusi", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("IdSurat")
                        .HasColumnType("bigint")
                        .HasColumnName("id_surat");

                    b.Property<string>("Jabatan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("jabatan");

                    b.Property<string>("Nama")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama");

                    b.Property<string>("Nik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nik");

                    b.Property<string>("Tipe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipe");

                    b.HasKey("Id");

                    b.HasIndex("IdSurat");

                    b.ToTable("surat_distribusi", "office", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SsoBackend.Models.Office.SuratLampiran", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DibuatPada")
                        .HasColumnType("datetime2")
                        .HasColumnName("dibuat_pada");

                    b.Property<long>("IdSurat")
                        .HasColumnType("bigint")
                        .HasColumnName("id_surat");

                    b.Property<string>("NamaFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama_file");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("path");

                    b.Property<string>("Tipe")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipe");

                    b.Property<long?>("Ukuran")
                        .HasColumnType("bigint")
                        .HasColumnName("ukuran");

                    b.HasKey("Id");

                    b.HasIndex("IdSurat");

                    b.ToTable("surat_lampiran", "office", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SsoBackend.Models.Office.SuratPj", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("IdSurat")
                        .HasColumnType("bigint")
                        .HasColumnName("id_surat");

                    b.Property<string>("Jabatan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("jabatan");

                    b.Property<string>("Komentar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("komentar");

                    b.Property<string>("Nama")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama");

                    b.Property<string>("Nik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nik");

                    b.Property<string>("Peran")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("peran");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("Tgl")
                        .HasColumnType("datetime2")
                        .HasColumnName("tgl");

                    b.Property<int>("Urutan")
                        .HasColumnType("int")
                        .HasColumnName("urutan");

                    b.HasKey("Id");

                    b.HasIndex("IdSurat");

                    b.ToTable("surat_pj", "office", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SsoBackend.Models.Office.SuratRiwayat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Aksi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("aksi");

                    b.Property<string>("Catatan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("catatan");

                    b.Property<long>("IdSurat")
                        .HasColumnType("bigint")
                        .HasColumnName("id_surat");

                    b.Property<string>("OlehNama")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("oleh_nama");

                    b.Property<string>("OlehNik")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("oleh_nik");

                    b.Property<DateTime>("Tgl")
                        .HasColumnType("datetime2")
                        .HasColumnName("tgl");

                    b.HasKey("Id");

                    b.HasIndex("IdSurat");

                    b.ToTable("surat_riwayat", "office", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SsoBackend.Models.Office.SuratTindakLanjut", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Catatan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("catatan");

                    b.Property<string>("DariNama")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dari_nama");

                    b.Property<string>("DariNik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dari_nik");

                    b.Property<long>("IdSurat")
                        .HasColumnType("bigint")
                        .HasColumnName("id_surat");

                    b.Property<string>("Keterangan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("keterangan");

                    b.Property<string>("NamaLampiran")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama_lampiran");

                    b.Property<string>("PathLampiran")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("path_lampiran");

                    b.Property<DateTime>("Tgl")
                        .HasColumnType("datetime2")
                        .HasColumnName("tgl");

                    b.Property<string>("Tipe")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipe");

                    b.Property<long?>("Ukuran")
                        .HasColumnType("bigint")
                        .HasColumnName("ukuran");

                    b.Property<string>("UntukNama")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("untuk_nama");

                    b.Property<string>("UntukNik")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("untuk_nik");

                    b.HasKey("Id");

                    b.ToTable("surat_tindak_lanjut", "office", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SsoBackend.Models.Prosedur.ProsedurAcknowledgement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("IdDokumen")
                        .HasColumnType("bigint")
                        .HasColumnName("id_dokumen");

                    b.Property<long>("IdVersi")
                        .HasColumnType("bigint")
                        .HasColumnName("id_versi");

                    b.Property<string>("Nama")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama");

                    b.Property<string>("Nik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nik");

                    b.Property<DateTime>("Tgl")
                        .HasColumnType("datetime2")
                        .HasColumnName("tgl");

                    b.HasKey("Id");

                    b.ToTable("acknowledgement", "prosedur", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SsoBackend.Models.Prosedur.ProsedurDokumen", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Deskripsi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("deskripsi");

                    b.Property<string>("IdPembuat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("id_pembuat");

                    b.Property<string>("Jenis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("jenis");

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("judul");

                    b.Property<string>("Kategori")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kategori");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kode");

                    b.Property<DateTime>("TglDibuat")
                        .HasColumnType("datetime2")
                        .HasColumnName("tgl_dibuat");

                    b.Property<DateTime?>("TglDiubah")
                        .HasColumnType("datetime2")
                        .HasColumnName("tgl_diubah");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.ToTable("dokumen", "prosedur", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SsoBackend.Models.Prosedur.ProsedurVersi", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("IdDokumen")
                        .HasColumnType("bigint")
                        .HasColumnName("id_dokumen");

                    b.Property<string>("IdPenerbit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("id_penerbit");

                    b.Property<byte[]>("Konten")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("konten");

                    b.Property<string>("NamaFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama_file");

                    b.Property<string>("NamaPenerbit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama_penerbit");

                    b.Property<string>("Ringkasan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ringkasan");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<DateOnly?>("TglBerlaku")
                        .HasColumnType("date")
                        .HasColumnName("tgl_berlaku");

                    b.Property<DateTime>("TglUnggah")
                        .HasColumnType("datetime2")
                        .HasColumnName("tgl_unggah");

                    b.Property<string>("TipeFile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipe_file");

                    b.Property<int>("Versi")
                        .HasColumnType("int")
                        .HasColumnName("versi");

                    b.HasKey("Id");

                    b.ToTable("versi", "prosedur", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SsoBackend.Models.Tugas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Deskripsi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("deskripsi");

                    b.Property<DateTime>("DibuatPada")
                        .HasColumnType("datetime2")
                        .HasColumnName("dibuat_pada");

                    b.Property<DateTime>("DiperbaruiPada")
                        .HasColumnType("datetime2")
                        .HasColumnName("diperbarui_pada");

                    b.Property<string>("IdPemberi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("id_pemberi");

                    b.Property<string>("IdPenerima")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("id_penerima");

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("judul");

                    b.Property<string>("NamaPemberi")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nama_pemberi");

                    b.Property<string>("NamaPenerima")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nama_penerima");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<DateOnly?>("Tenggat")
                        .HasColumnType("date")
                        .HasColumnName("tenggat");

                    b.HasKey("Id");

                    b.ToTable("tugas", "myteam", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SsoBackend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SsoBackend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SsoBackend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SsoBackend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Authorizations")
                        .HasForeignKey("ApplicationId");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationId");

                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", "Authorization")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationId");

                    b.Navigation("Application");

                    b.Navigation("Authorization");
                });

            modelBuilder.Entity("SsoBackend.Models.Office.SuratDistribusi", b =>
                {
                    b.HasOne("SsoBackend.Models.Office.Surat", null)
                        .WithMany("Distribusi")
                        .HasForeignKey("IdSurat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SsoBackend.Models.Office.SuratLampiran", b =>
                {
                    b.HasOne("SsoBackend.Models.Office.Surat", null)
                        .WithMany("Lampiran")
                        .HasForeignKey("IdSurat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SsoBackend.Models.Office.SuratPj", b =>
                {
                    b.HasOne("SsoBackend.Models.Office.Surat", null)
                        .WithMany("PenanggungJawab")
                        .HasForeignKey("IdSurat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SsoBackend.Models.Office.SuratRiwayat", b =>
                {
                    b.HasOne("SsoBackend.Models.Office.Surat", null)
                        .WithMany("Riwayat")
                        .HasForeignKey("IdSurat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("SsoBackend.Models.Office.Surat", b =>
                {
                    b.Navigation("Distribusi");

                    b.Navigation("Lampiran");

                    b.Navigation("PenanggungJawab");

                    b.Navigation("Riwayat");
                });
#pragma warning restore 612, 618
        }
    }
}
